name: garden_planner_app
description: Garden planner application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.1"

dependencies:
  badges: ^2.0.3
  camera: ^0.9.8
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_material_pickers: ^3.1.4+1
  flutter_svg: ^1.1.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  image_picker: ^0.8.5+3
  path: ^1.8.1
  path_provider: ^2.0.11
  provider: ^6.0.3
  table_calendar: ^3.0.6
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.11
  dart_code_metrics: ^4.15.2
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
  - family: Roboto Sans
    fonts:
    - asset: fonts/Roboto-Light.ttf